"""Edit created_at and updated_at in StockLevel

Revision ID: 5f2967cd2d80
Revises: 6df60e38e8ee
Create Date: 2024-09-15 14:39:57.436175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5f2967cd2d80'
down_revision: Union[str, None] = '6df60e38e8ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
