"""Add association table

Revision ID: fafc59c942fe
Revises: cb07561e7d94
Create Date: 2024-09-17 19:56:07.483991

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fafc59c942fe'
down_revision: Union[str, None] = 'cb07561e7d94'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('item_suppliers',
    sa.Column('item_id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['item_id'], ['items.id'], name=op.f('fk_item_suppliers_item_id_items')),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], name=op.f('fk_item_suppliers_supplier_id_suppliers')),
    sa.PrimaryKeyConstraint('item_id', 'supplier_id')
    )
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('items', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=False)
    op.alter_column('stocklevels', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('suppliers', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('suppliers', 'contact',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('suppliers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('stocklevels', 'quantity',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('items', 'price',
               existing_type=sa.DECIMAL(precision=10, scale=2),
               nullable=True)
    op.alter_column('items', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('categories', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_table('item_suppliers')
    # ### end Alembic commands ###
